x=10
try:
    print(y)
except:
    print("Something Went wrong")
finally:
    print("The try except is finished")
